In [1]:
import pandas as pd
import random
import os
import json

In [2]:
df = pd.read_csv("../files/Copy of cleaned_oops(1).csv")

In [3]:
df

,Unnamed: 0,Unnamed: 1,Quiz1,Quiz1.1,Mid Sem,Q1,Q2,Q3,Q4,Q5,...,Q3.1,Q4.1,Q5.1,Q6.1,Q7.1,Part2 Total,CBT Total,Matched ID,Match Status,Folder Name
0,NaN,NaN,NaN,NaN,37.5,2.0,8.0,4.0,5.0,5.0,...,5.0,4.0,4.0,2.0,5.0,39.5,73.5,2022B3A70426P,Green,1181
1,NaN,NaN,NaN,NaN,53.5,2.0,9.0,4.0,5.0,4.0,...,5.0,4.0,4.0,2.0,5.0,39.0,70.5,2023A7PS0629P,Green,1177
2,NaN,NaN,NaN,NaN,47.0,2.0,9.0,3.0,5.0,5.0,...,4.0,4.0,4.0,2.0,4.0,36.5,70.5,2023A7PS0656P,Green,1184
3,NaN,NaN,NaN,NaN,55.0,2.0,9.0,4.0,5.0,5.0,...,4.0,4.0,4.0,2.0,4.0,35.0,70.0,2022A8PS1260P,Green,1269
4,NaN,NaN,NaN,NaN,51.0,2.0,9.0,4.0,4.0,3.0,...,5.0,4.0,4.0,2.0,5.0,39.5,69.5,2023A7PS0570P,Green,1026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,NaN,NaN,NaN,NaN,17.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2022B3A70474P,Green,1188
297,NaN,NaN,NaN,NaN,34.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2022B2A71101P,Green,1209
298,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023A7PS0509P,Green,1256
299,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023A7PS0533P,Yellow,1312
300,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023A7PS0635P,Yellow,1314

In [4]:
df = df[(df['Part1 Total'] >= 20) & (df['Part1 Total']<30)]

In [5]:
df

,Unnamed: 0,Unnamed: 1,Quiz1,Quiz1.1,Mid Sem,Q1,Q2,Q3,Q4,Q5,...,Q3.1,Q4.1,Q5.1,Q6.1,Q7.1,Part2 Total,CBT Total,Matched ID,Match Status,Folder Name
22,NaN,NaN,NaN,NaN,27.0,2.0,6.0,4.0,4.0,1.5,...,2.0,4.0,4.0,2.0,2.0,33.0,59.5,2022B3A71033P,Green,1051
23,NaN,NaN,NaN,NaN,63.0,2.0,7.0,3.4,3.0,3.0,...,4.0,4.0,4.0,2.0,4.0,33.0,59.4,2023A7PS0021P,Green,1203
27,NaN,NaN,NaN,NaN,39.5,2.0,5.0,3.0,4.0,5.0,...,4.0,3.5,4.0,2.0,0.0,29.5,58.5,2023A7PS0498P,Green,1085
32,NaN,NaN,NaN,NaN,0.0,2.0,5.0,4.0,5.0,4.0,...,4.0,4.0,4.0,2.0,3.0,30.0,58.0,2022A7PS0136P,Green,1236
37,NaN,NaN,NaN,NaN,62.0,2.0,9.0,4.0,4.0,2.0,...,2.0,4.0,4.0,2.0,4.0,28.0,56.0,2022B3A70495P,Green,1063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,NaN,NaN,NaN,NaN,18.0,2.0,9.0,4.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,1.0,23.0,2022A3PS1206P,Green,1090
174,NaN,NaN,NaN,NaN,8.5,2.0,5.0,3.0,5.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,23.0,2022B4A70804P,Green,1261
177,NaN,NaN,NaN,NaN,0.0,2.0,8.0,0.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,0.0,21.0,2022A7PS0109P,Green,1125
179,NaN,NaN,NaN,NaN,16.5,1.0,2.5,4.0,3.0,2.5,...,0.0,0.0,0.0,0.0,0.0,0.0,20.0,2023A7PS0567P,Green,1055
181,NaN,NaN,NaN,NaN,44.0,2.0,3.0,2.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,0.0,20.0,2021A3PS2651P,Green,1197

In [6]:
random_sample = df.sample(n=17, random_state=20)
random_sample[['Part1 Total', 'Folder Name']]

     Part1 Total  Folder Name
132         27.5         1011
107         24.0         1275
114         29.0         1254
166         21.0         1215
171         22.0         1090
113         23.5         1289
22          26.5         1051
102         28.5         1001
85          24.0         1148
39          23.0         1193
179         20.0         1055
57          28.0         1149
109         25.0         1111
142         28.5         1283
27          29.0         1085
156         26.0         1073
90          27.0         1159

In [8]:
basePath = '../files/solutions_cleaned/'
selectedPath = '../files/selected_solutions/'
if not os.path.exists(selectedPath):
    os.mkdir(selectedPath)

infoDict = {}

for index, row in random_sample.iterrows():
    marks = row["Part1 Total"]
    folder = str(row['Folder Name'])
    infoDict[folder] = {}
    for i in range(1, 8):
        infoDict[folder]['Q'+str(i)] = row['Q'+str(i)]
    print(marks, folder)
    with open(basePath+folder+"/p1.java", "r") as file:
        code = file.read()
    with open(selectedPath+folder+".java", "w") as file:
        file.write(code)
    infoDict[folder]["Total"] = marks

with open(selectedPath+"info.json", "w") as file:
    json.dump(infoDict, file)

27.5 1011
24.0 1275
29.0 1254
21.0 1215
22.0 1090
23.5 1289
26.5 1051
28.5 1001
24.0 1148
23.0 1193
20.0 1055
28.0 1149
25.0 1111
28.5 1283
29.0 1085
26.0 1073
27.0 1159

In [12]:
with open(selectedPath+"out.csv", "w") as file:
    head = 'Solution, '
    for i in range(1, 8):
        head+='Q'+str(i)+', '
    head += 'Total, \n'
    file.write(head)
    for key in infoDict:
        writeStr = str(key)+', '
        for i in range(1, 8):
            writeStr += str(infoDict[key]['Q'+str(i)])+', '
        writeStr += str(infoDict[key]["Total"])
        file.write(writeStr)
        file.write('\n')